# PROW_INSTANCE_SPECIFIC
# Very customized metrics endpoints
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: falco
stringData:
  prometheus-additional.yaml: |
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://falco.prow.org
          - https://download.falco.org
          - https://falco.org
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-prober
    - job_name: falco 
      static_configs: 
        - targets: ["falco-exporter:9376"]
    - job_name: falcosidekick
      metrics_path: /metrics
      static_configs: 
        - targets: ["falcosidekick:2801"] 
type: Opaque
